version: '3'
networks:
  von:
services:

  issuer-agent:
    image: bcgovimages/aries-cloudagent:py3.12_1.0.0rc5
    ports:
      - 11000:11000
      - 8001:8001
    entrypoint: /bin/bash
    command: [
        "-c",
        "sleep 5; \
        aca-py start \
        --auto-provision \
        --seed 'issuer00000000000000000000000001' \
        --inbound-transport http '0.0.0.0' 8001 \
        --endpoint 'http://issuer-agent:8001' \
        --outbound-transport http \
        --genesis-url 'http://webserver:8000/genesis' \
        --auto-accept-invites \
        --replace-public-did  \
        --wallet-allow-insecure-seed  \
        --wallet-local-did	\
        --auto-accept-requests \
        --auto-ping-connection \
        --auto-respond-messages \
        --auto-respond-credential-proposal \
        --auto-store-credential \
        --auto-respond-credential-offer \
        --auto-respond-credential-request \
        --notify-revocation \
        --monitor-revocation-notification \
        --wallet-type 'askar' \
        --wallet-name 'issuer_agent_wallet' \
        --wallet-key 'key' \
        --admin '0.0.0.0' 11000 \
        --admin-insecure-mode \
        --label 'issuer' \
        --log-level 'info' ",
        --plugin aries_cloudagent.messaging.jsonld.jsonld_plugin \
        --public-invites \
        --public-dids      
      ]
    # volumes:
    #   - ./aca-py-config.yaml:/usr/aca-py-config.yaml
    networks:
      - von



  verifier-agent:
    image: bcgovimages/aries-cloudagent:py3.12_1.0.0rc5
    ports:
      - 11001:11000
      - 8002:8001
    entrypoint: /bin/bash
    command: [
        "-c",
        "sleep 5; \
        aca-py start \        
        --auto-provision \
        --seed 'verifi00000000000000000000000001' \
        --inbound-transport http '0.0.0.0' 8001 \
        --endpoint 'http://verifier-agent:8001' \
        --outbound-transport http \
        --genesis-url 'http://webserver:8000/genesis' \
        --auto-accept-invites \
        --replace-public-did  \
        --wallet-allow-insecure-seed  \
        --wallet-local-did	\
        --auto-accept-requests \
        --auto-ping-connection \
        --auto-respond-messages \
        --auto-respond-credential-proposal \
        --auto-store-credential \
        --auto-respond-credential-offer \
        --auto-respond-credential-request \
        --notify-revocation \
        --monitor-revocation-notification \
        --wallet-type 'askar' \
        --wallet-name 'verifier_agent_wallet' \
        --wallet-key 'key' \
        --admin '0.0.0.0' 11000 \
        --admin-insecure-mode \
        --label 'Verifier' \
        --log-level 'info' ",
        --plugin aries_cloudagent.messaging.jsonld.jsonld_plugin \
        --public-invites \
        --public-dids         
      ]
    # volumes:
    #   - ./aca-py-config.yaml:/usr/aca-py-config.yaml    
    networks:
      - von


  holder-agent:
    image: bcgovimages/aries-cloudagent:py3.12_1.0.0rc5
    ports:
      - 11003:11000
      - 8003:8001
    entrypoint: /bin/bash
    command: [
        "-c",
        "sleep 5; \
        aca-py start \        
        --auto-provision \
        --seed 'holder00000000000000000000000001' \
        --inbound-transport http '0.0.0.0' 8001 \
        --endpoint 'http://holder-agent:8001' \
        --outbound-transport http \
        --genesis-url 'http://webserver:8000/genesis' \
        --auto-accept-invites \
        --auto-accept-requests \
        --auto-ping-connection \
        --auto-respond-messages \
        --replace-public-did  \
        --wallet-allow-insecure-seed  \
        --wallet-local-did	\
        --auto-respond-credential-proposal \
        --auto-store-credential \
        --auto-respond-credential-offer \
        --auto-respond-credential-request \
        --notify-revocation \
        --monitor-revocation-notification \
        --wallet-type 'askar' \
        --wallet-name 'holder_agent_wallet' \
        --wallet-key 'key' \
        --admin '0.0.0.0' 11000 \
        --admin-insecure-mode \
        --label 'holder' \
        --log-level 'info' ",
        --plugin aries_cloudagent.messaging.jsonld.jsonld_plugin \
        --public-invites \
        --public-dids           
      ]
    # volumes:
    #   - ./aca-py-config.yaml:/usr/aca-py-config.yaml    
    networks:
      - von



  # wallet-db:
  #   image: postgres:12
  #   environment:
  #     - POSTGRES_USER=DB_USER
  #     - POSTGRES_PASSWORD=DB_PASSWORD
  #   ports:
  #     - 5432:5432
  #   volumes:
  #     - wallet-db-data:/var/lib/pgsql/data
  #   networks:
  #     - von

# volumes:
#   wallet-db-data:
